const CONTEXT_TYPE = {
  NEW_SEARCH: 'NEW_SEARCH',
  RESET_SEARCH: 'RESET_SEARCH',
  MERGE_SEARCH: 'MERGE_SEARCH'
}

const MILLISECONDS_PER_DAY = 1000 * 60 * 60 * 24;

const AUTH_CONTEXT_TYPE = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT'
}

export { 
  CONTEXT_TYPE,
  MILLISECONDS_PER_DAY,
  AUTH_CONTEXT_TYPE
}